name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init-test:
    runs-on: ubuntu-latest

    env:
      ports: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    services:
     mongo:
      image: mongo
      ports: ['27017:27017']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
           node-version: '18'


      - name: Wait for MongoDB to be ready
        run: |
           until nc -z localhost 27017; do
             echo "waiting for mongodb"
             sleep 2
            done
             echo "mongodb is up"

      - name: Seed MongoDB
        working-directory: ././backend
        run: |
          npm install
          node seedTasksData.js

      - name: Running backend tests
        working-directory: ././backend
        run: npm test
  